### PR TITLE
added all arangoDB constructor arguments

### PR DESCRIPTION
**Pull request by rashtao**

### CODE REVIEW

**Comment by rashtao** [comment]
Unfortunately such features are quite hard to test... I did it manually using docker containers and exporting then the nifi template here: https://github.com/rashtao/nifi-arangodb-bundle/tree/docker_deployment/test_deployment

**Comment by rashtao** [comment]
I have also enabled org.apache.nifi.processor.QueryArangoDB processor since it was not exposed in the manifest file.

**Review by MikeThomsen — APPROVED** [review]
LGTM

**Comment by MikeThomsen** [comment]
Thanks!

**Pull request merged**
